export const ACTIONS = {
	CYRRENCY_SWITCH: 'CYRRENCY_SWITCH',
	CYRRENCY_CHECK: 'CYRRENCY_CHECK',
	CYRRENCY_SET_BY_USER: 'CYRRENCY_SET_BY_USER',

	OPEN_MODAL: 'OPEN_MODAL',
	CLOSE_MODAL: 'CLOSE_MODAL',

	OPEN_USER_MODAL: 'OPEN_USER_MODAL',
	CLOSE_USER_MODAL: 'CLOSE_USER_MODAL',

	OPEN_ADD_ACCOUNT_MODAL: 'OPEN_ADD_ACCOUNT_MODAL',
	CLOSE_ADD_ACCOUNT_MODAL: 'CLOSE_ADD_ACCOUNT_MODAL',

	OPEN_UPDATE_ACCOUNT_MODAL: 'OPEN_UPDATE_ACCOUNT_MODAL',
	CLOSE_UPDATE_ACCOUNT_MODAL: 'CLOSE_UPDATE_ACCOUNT_MODAL',

	OPEN_ADD_CATEGORY_MODAL: 'OPEN_ADD_CATEGORY_MODAL',
	CLOSE_ADD_CATEGORY_MODAL: 'CLOSE_ADD_CATEGORY_MODAL',

	OPEN_UPDATE_CATEGORY_MODAL: 'OPEN_UPDATE_CATEGORY_MODAL',
	CLOSE_UPDATE_CATEGORY_MODAL: 'CLOSE_UPDATE_CATEGORY_MODAL',

	OPEN_OPERATION_MODAL: 'OPEN_OPERATION_MODAL',
	CLOSE_OPERATION_MODAL: 'CLOSE_OPERATION_MODAL',

	OPEN_CRYPTO_OPERATION_MODAL: 'OPEN_CRYPTO_OPERATION_MODAL',
	CLOSE_CRYPTO_OPERATION_MODAL: 'CLOSE_CRYPTO_OPERATION_MODAL',

	OPEN_BURGER_MODAL: 'OPEN_BURGER_MODAL',
	CLOSE_BURGER_MODAL: 'CLOSE_BURGER_MODAL',

	FETCH_HISTORY_REQUEST: 'FETCH_HISTORY_REQUEST',
	FETCH_HISTORY_SUCCESS: 'FETCH_HISTORY_SUCCESS',
	FETCH_HISTORY_ERROR: 'FETCH_HISTORY_ERROR',
	CLEAR_HISTORY_DATA: 'CLEAR_HISTORY_DATA',

	FETCH_CRYPTODATA_REQUEST: 'FETCH_CRYPTODATA_REQUEST',
	FETCH_CRYPTODATA_SUCCESS: 'FETCH_CRYPTODATA_SUCCESS',
	FETCH_CRYPTODATA_ERROR: 'FETCH_CRYPTODATA_ERROR',
	CLEAR_CRYPTODATA_DATA: 'CLEAR_CRYPTODATA_DATA',

	FETCH_ACCOUNTS_REQUEST: 'FETCH_ACCOUNTS_REQUEST',
	FETCH_ACCOUNTS_SUCCESS: 'FETCH_ACCOUNTS_SUCCESS',
	FETCH_ACCOUNTS_ERROR: 'FETCH_ACCOUNTS_ERROR',
	CLEAR_ACCOUNTS_DATA: 'CLEAR_ACCOUNTS_DATA',

	FETCH_CATEGORIES_REQUEST: 'FETCH_CATEGORIES_REQUEST',
	FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
	FETCH_CATEGORIES_ERROR: 'FETCH_CATEGORIES_ERROR',
	CLEAR_CATEGORIES_DATA: 'CLEAR_CATEGORIES_DATA',

	GET_USER_DATA: 'GET_USER_DATA',
	USER_SET_LOADING: 'USER_SET_LOADING',
	CLEAR_USER_DATA: 'CLEAR_USER_DATA',

	TOGGLE_THEME: 'TOGGLE_THEME',
};
