export const ACTIONS = {
	CYRRENCY_SWITCH: 'CYRRENCY_SWITCH',
	CYRRENCY_CHECK: 'CYRRENCY_CHECK',

	OPEN_MODAL: 'OPEN_MODAL',
	CLOSE_MODAL: 'CLOSE_MODAL',

	OPEN_ADD_ACCOUNT_MODAL: 'OPEN_ADD_ACCOUNT_MODAL',
	CLOSE_ADD_ACCOUNT_MODAL: 'CLOSE_ADD_ACCOUNT_MODAL',

	OPEN_OPERATION_MODAL: 'OPEN_OPERATION_MODAL',
	CLOSE_OPERATION_MODAL: 'CLOSE_OPERATION_MODAL',
	OPEN_BURGER_MODAL: 'OPEN_BURGER_MODAL',
	CLOSE_BURGER_MODAL: 'CLOSE_BURGER_MODAL',

	FETCH_HISTORY_REQUEST: 'FETCH_HISTORY_REQUEST',
	FETCH_HISTORY_SUCCESS: 'FETCH_HISTORY_SUCCESS',
	FETCH_HISTORY_ERROR: 'FETCH_HISTORY_ERROR',

	FETCH_CRYPTODATA_REQUEST: 'FETCH_CRYPTODATA_REQUEST',
	FETCH_CRYPTODATA_SUCCESS: 'FETCH_CRYPTODATA_SUCCESS',
	FETCH_CRYPTODATA_ERROR: 'FETCH_CRYPTODATA_ERROR',

	FETCH_ACCOUNTS_REQUEST: 'FETCH_ACCOUNTS_REQUEST',
	FETCH_ACCOUNTS_SUCCESS: 'FETCH_ACCOUNTS_SUCCESS',
	FETCH_ACCOUNTS_ERROR: 'FETCH_ACCOUNTS_ERROR',

	FETCH_CATEGORIES_REQUEST: 'FETCH_CATEGORIES_REQUEST',
	FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
	FETCH_CATEGORIES_ERROR: 'FETCH_CATEGORIES_ERROR',

	GET_USER_DATA: 'GET_USER_DATA',
	CLEAR_USER_DATA: 'CLEAR_USER_DATA',
};
