export const ACTIONS = {
	CYRRENCY_SWITCH: 'CYRRENCY_SWITCH',
	CYRRENCY_CHECK: 'CYRRENCY_CHECK',

	OPEN_MODAL: 'OPEN_MODAL',
	CLOSE_MODAL: 'CLOSE_MODAL',

	FETCH_HISTORY_REQUEST: 'FETCH_HISTORY_REQUEST',
	FETCH_HISTORY_SUCCESS: 'FETCH_HISTORY_SUCCESS',
	FETCH_HISTORY_ERROR: 'FETCH_HISTORY_ERROR',

	FETCH_CRYPTOHISTORY_REQUEST: 'FETCH_CRYPTOHISTORY_REQUEST',
	FETCH_CRYPTOHISTORY_SUCCESS: 'FETCH_CRYPTOHISTORY_SUCCESS',
	FETCH_CRYPTOHISTORY_ERROR: 'FETCH_CRYPTOHISTORY_ERROR',
};
