export const MODAL_TYPES = {
	BURGER_MENU: 'BURGER_MENU',
	ADD_ACCOUNT: 'ADD_ACCOUNT',
	UPDATE_ACCOUNT: 'UPDATE_ACCOUNT',
	ADD_CATEGORY: 'ADD_CATEGORY',
	UPDATE_CATEGORY: 'UPDATE_CATEGORY',
	ADD_CRYPTO_ASSET: 'ADD_CRYPTO_ASSET',
	UPDATE_CRYPTO_ASSET: 'UPDATE_CRYPTO_ASSET',
	OPERATION: 'OPERATION',
	CRYPTO_OPERATION: 'CRYPTO_OPERATION',
	USER_SETTINGS: 'USER_SETTINGS',
};
